'use client';

import { Calendar, User, FileBarChart, Download, Printer, Share2 } from 'lucide-react';
import {
    Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle,
} from "@/components/ui/sheet";
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { format } from 'date-fns';

interface Report {
    id: string;
    name: string;
    type: string;
    generatedBy: string;
    generatedAt: string;
    status: string;
    size: string;
    description: string;
}

interface SchoolReportViewSheetProps {
    report: Report | null;
    open: boolean;
    onOpenChange: (open: boolean) => void;
}

export function SchoolReportViewSheet({ report, open, onOpenChange }: SchoolReportViewSheetProps) {
    if (!report) return null;

    return (
        <Sheet open={open} onOpenChange={onOpenChange}>
            <SheetContent className="overflow-y-auto sm:max-w-md">
                <SheetHeader>
                    <SheetTitle>Report Details</SheetTitle>
                    <SheetDescription>Detailed metadata and actions.</SheetDescription>
                </SheetHeader>
                <div className="space-y-6 py-6">
                    <div className="space-y-4">
                        <div className="flex items-center gap-3">
                            <div className="h-10 w-10 rounded bg-primary/10 flex items-center justify-center text-primary">
                                <FileBarChart className="h-5 w-5" />
                            </div>
                            <div>
                                <h3 className="font-semibold text-lg leading-tight">{report.name}</h3>
                                <p className="text-sm text-muted-foreground">{report.type} Report</p>
                            </div>
                        </div>

                        <div className="bg-muted/50 p-3 rounded-md text-sm text-muted-foreground">
                            {report.description}
                        </div>

                        <div className="grid grid-cols-2 gap-4 text-sm">
                            <div className="space-y-1">
                                <span className="text-xs text-muted-foreground block">Generated On</span>
                                <div className="flex items-center gap-1 font-medium">
                                    <Calendar className="h-3.5 w-3.5" />
                                    {format(new Date(report.generatedAt), 'MMM d, yyyy')}
                                </div>
                            </div>
                            <div className="space-y-1">
                                <span className="text-xs text-muted-foreground block">File Size</span>
                                <div className="font-medium">{report.size}</div>
                            </div>
                            <div className="space-y-1">
                                <span className="text-xs text-muted-foreground block">Generated By</span>
                                <div className="flex items-center gap-1 font-medium">
                                    <User className="h-3.5 w-3.5" />
                                    {report.generatedBy}
                                </div>
                            </div>
                            <div className="space-y-1">
                                <span className="text-xs text-muted-foreground block">Status</span>
                                <Badge variant={report.status === 'Ready' ? 'default' : 'secondary'} className="w-fit">
                                    {report.status}
                                </Badge>
                            </div>
                        </div>
                    </div>
                    <Separator />
                    <div className="space-y-3">
                        <h4 className="text-sm font-semibold">Actions</h4>
                        <div className="grid grid-cols-2 gap-3">
                            <Button className="w-full" disabled={report.status !== 'Ready'}>
                                <Download className="mr-2 h-4 w-4" /> Download PDF
                            </Button>
                            <Button variant="outline" className="w-full" disabled={report.status !== 'Ready'}>
                                <Printer className="mr-2 h-4 w-4" /> Print
                            </Button>
                        </div>
                        <Button variant="secondary" className="w-full">
                            <Share2 className="mr-2 h-4 w-4" /> Share with Staff
                        </Button>
                    </div>
                </div>
            </SheetContent>
        </Sheet>
    );
}
