'use client';

import {
    FileText, Calendar, Clock, Eye, MoreVertical, Download, Share2,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
    Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from "@/components/ui/table";
import {
    DropdownMenu, DropdownMenuContent, DropdownMenuItem,
    DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { format } from 'date-fns';

interface Report {
    id: string;
    name: string;
    type: string;
    generatedBy: string;
    generatedAt: string;
    status: string;
    size?: string;
    description: string;
}

interface SchoolReportTableProps {
    reports: Report[];
    onView: (report: Report) => void;
}

export function SchoolReportTable({ reports, onView }: SchoolReportTableProps) {
    return (
        <div className="rounded-md border">
            <Table>
                <TableHeader>
                    <TableRow>
                        <TableHead>Report Name</TableHead>
                        <TableHead>Type</TableHead>
                        <TableHead>Generated By</TableHead>
                        <TableHead>Date & Time</TableHead>
                        <TableHead>Size</TableHead>
                        <TableHead>Status</TableHead>
                        <TableHead className="text-right">Actions</TableHead>
                    </TableRow>
                </TableHeader>
                <TableBody>
                    {reports.length === 0 ? (
                        <TableRow>
                            <TableCell colSpan={7} className="h-24 text-center">
                                No reports found matching your filters.
                            </TableCell>
                        </TableRow>
                    ) : (
                        reports.map((report) => (
                            <TableRow
                                key={report.id}
                                className="cursor-pointer hover:bg-muted/50"
                                onClick={(e) => {
                                    if ((e.target as any).closest('.action-btn')) return;
                                    onView(report);
                                }}
                            >
                                <TableCell className="font-medium text-foreground">
                                    <div className="flex items-center gap-2">
                                        <FileText className="h-4 w-4 text-muted-foreground" />
                                        {report.name}
                                    </div>
                                </TableCell>
                                <TableCell>
                                    <Badge variant="outline">{report.type}</Badge>
                                </TableCell>
                                <TableCell className="text-muted-foreground text-sm">
                                    {report.generatedBy}
                                </TableCell>
                                <TableCell className="text-muted-foreground text-sm">
                                    <div className="flex items-center gap-1">
                                        <Calendar className="h-3 w-3" />
                                        {format(new Date(report.generatedAt), 'MMM d, yyyy')}
                                        <span className="hidden sm:inline">
                                            <Clock className="h-3 w-3 ml-2 inline" />
                                            {format(new Date(report.generatedAt), 'h:mm a')}
                                        </span>
                                    </div>
                                </TableCell>
                                <TableCell className="text-muted-foreground text-sm">{report.size || '-'}</TableCell>
                                <TableCell>
                                    <Badge variant={report.status === 'Ready' ? 'default' : 'secondary'}
                                        className={report.status === 'Ready' ? 'bg-green-100 text-green-800 hover:bg-green-100 border-green-200' : ''}
                                    >
                                        {report.status}
                                    </Badge>
                                </TableCell>
                                <TableCell className="text-right">
                                    <DropdownMenu>
                                        <DropdownMenuTrigger asChild>
                                            <Button variant="ghost" className="h-8 w-8 p-0 action-btn">
                                                <span className="sr-only">Open menu</span>
                                                <MoreVertical className="h-4 w-4" />
                                            </Button>
                                        </DropdownMenuTrigger>
                                        <DropdownMenuContent align="end">
                                            <DropdownMenuLabel>Actions</DropdownMenuLabel>
                                            <DropdownMenuItem onClick={() => onView(report)}>
                                                <Eye className="mr-2 h-4 w-4" /> View Details
                                            </DropdownMenuItem>
                                            <DropdownMenuItem disabled={report.status !== 'Ready'}>
                                                <Download className="mr-2 h-4 w-4" /> Download
                                            </DropdownMenuItem>
                                            <DropdownMenuSeparator />
                                            <DropdownMenuItem>
                                                <Share2 className="mr-2 h-4 w-4" /> Share
                                            </DropdownMenuItem>
                                        </DropdownMenuContent>
                                    </DropdownMenu>
                                </TableCell>
                            </TableRow>
                        ))
                    )}
                </TableBody>
            </Table>
        </div>
    );
}
