// Sanity schema: Report document type
import { defineField, defineType } from 'sanity';

export default defineType({
    name: 'report',
    title: 'Report',
    type: 'document',
    fields: [
        defineField({ name: 'customId', title: 'Custom ID', type: 'string', validation: r => r.required() }),
        defineField({ name: 'name', title: 'Name', type: 'string' }),
        defineField({ name: 'reportType', title: 'Type', type: 'string' }),
        defineField({ name: 'generatedBy', title: 'Generated By', type: 'string' }),
        defineField({ name: 'generatedAt', title: 'Generated At', type: 'string' }),
        defineField({
            name: 'status', title: 'Status', type: 'string',
            options: { list: ['Ready', 'Processing', 'Failed'] }
        }),
        defineField({ name: 'size', title: 'Size', type: 'string' }),
        defineField({ name: 'description', title: 'Description', type: 'text' }),
        defineField({ name: 'schoolId', title: 'School ID', type: 'string' }),
    ],
    preview: { select: { title: 'name', subtitle: 'status' } }
});
